### PR TITLE
Improvements suggestions

### PR DESCRIPTION
**Pull request by tbranyen**
Very nice implementation! Saw this on Hacker News and a few minor things were bothering me so I decided to open a PR with distinct commits for you to look over.

- Removes an unnecessary window global, use strict pragma, and IIFE, these were distracting and unnecessary
- Mix of arrow function and function declarations, so I simplified those down, including the methods in the App object
- `_` prefix to a property typically denotes "private", yet the `init()` was called publicly, so the prefix is removed
- Improvements to toggleAll as there were too many conditionals
- Lastly two cosmetic changes around ASI and the template string

### CODE REVIEW

**Comment by 1Marc** [comment]
Cool, thanks!

**Comment by 1Marc** [comment]
These are all pretty great simplifications. Thanks!

The only thing I don't know if I agree with here is the IFFE and global. That was provided with TodoMVC's boilerplate.

I like to drop the App into the global namespace for debugging purposes, and the IFFE hides any variables inside that scope so they don't leak out to global.

**Comment by tbranyen** [comment]
> These are all pretty great simplifications. Thanks!
> 
> The only thing I don't know if I agree with here is the IFFE and global. That was provided with TodoMVC's boilerplate.
> 
> I like to drop the App into the global namespace for debugging purposes, and the IFFE hides any variables inside that scope so they don't leak out to global.

You are using ES modules. There are no global leaks per design. TodoMVC recommendations are based on scripts not modules.

**Comment by tbranyen** [comment]
@1Marc regarding the second part of your response, debugging in the console, if we were to add `export default app;` to the `js/app.js` file, you could then do:

```js
await import('./js/app.js').default
```

instead of:

```js
window.app
```

tbqh, I think it's fine to expose a global for testing purposes, we even do it for netflix. although in the future once we fully move to es modules, we'll probably opt for an `import()` path instead.

**Comment by tbranyen** [comment]
If you wanted to go a step further, you could use an import map:

```html
<script type="importmap">
{
  "imports": {
    "app": "/js/app.js"
  }
}
</script>
```

And then you get a cleaner way of importing, without having to memorize the path:

```js
(await import('app')).default
```

**Pull request merged**
